### ISSUE TITLE
@lazy not working with @autoinject

### ISSUE THREAD

**Issue by gronostajo** [aurelia/dependency-injection#153]
**I'm submitting a bug report**

* **Library Version:**
1.3.2

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.11.2

* **NPM Version:**
4.6.1

* **JSPM OR Webpack AND Version**
JSPM 0.16.48 (reproduced with Aurelia CLI v0.31.1)

* **Browser:**
all

* **Language:**
TypeScript 2.4.2

**Current behavior:**
Constructor arguments decorated with `@lazy` are injected with `undefined` when class is `@autoinject`ed. [Code](https://github.com/gronostajo/aurelia-dependency-injection-lazy-bug), [live demo](https://gronostajo.github.io/aurelia-dependency-injection-lazy-bug/).

**Expected/desired behavior:**

* **What is the expected behavior?**
`@autoinject` and `@lazy` should work well together. It probably was after #111 was merged.

* **What is the motivation / use case for changing the behavior?**
I want to be able to do this:

```
@autoinject
export class Alert {
  constructor(private i18n: I18N, @lazy(TemplatingEngine) private templatingEngine: () => TemplatingEngine) {
  }
}
```

**Comment by doktordirk** [comment]
anything new? that example is in the docs, so one could expect ir to work

**Comment by doktordirk** [comment]
i did some digging, and what i found is that autoinject naturally can't match eg type `lazy(HttpClient) with type ()=>HttpClient` and hence does not replace ()=>HttpClient with lazy(HttpClient) in the inject property, but adds it.

one seeming solution is to adjust the metadata of the target to the desired type for injection, in this case lazy(HttpClient). simple way would be

```js

/**
* Decorator: Specifies the dependency should be lazy loaded
*/
function lazy(keyValue: any) {
  return function(target, key, index) {
    let params = getDecoratorDependencies(target, 'lazy');
    params[index] = Lazy.of(keyValue);

    // added: adjust types in the metadata
    metadata.define(metadata.paramTypes, params, target);
  };
}
```

same in the other decorators. seemingly works fine, but i don't realy know the consequences particularly since eg inject + Lazy.of does not change the metadata.paramTypes in that way

**Comment by EisenbergEffect** [comment]
@doktordirk Interested in submitting a PR?

**Comment by doktordirk** [comment]
@EisenbergEffect as such sure, but that was a hack. 
i did dig further and found that this bug was introduced when fixing that issue #121 in pr #129.

my guess is that it got overboard there, and there wasn't anything else wrong other that the loop. it seems that they thought that the previousInject mentioned there was coming from a super class. instead it is (at least also) coming from the now bugged @lazy decorator which adds the inject property before @autoinject is called. 

would have been easier if PR+129  had included some tests for the presumed inheritance issue (resp @lazy would have had better tests). i might write some myself to see what happens

**Comment by EisenbergEffect** [comment]
@doktordirk If you are up to putting together some tests to asset both scenarios as part of trying to fix the issue, that would be awesome :)

**Comment by doktordirk** [comment]
@ccrd  yes, for all the resolver decorators, the type of the metadata and the inject property won't match and hence the current implementation of autoinject+resolver_decorators won't work.

@EisenbergEffect as such sure, but that was a hack.
anyways, i did dig further and found that this bug was introduced when fixing that issue #121 in pr #129. however, that issue highlights, that the design of @lazy et al., didn't took inheritance into account.  i'll see if i can find some solution

**Comment by EisenbergEffect** [comment]
Merged the fix :)
