### ISSUE TITLE
error TS1005: ';' expected in TS typings

### ISSUE THREAD

**Issue by fracz** [aurelia/dependency-injection#180]
**I'm submitting a bug report**

[This line](https://github.com/aurelia/dependency-injection/blob/fd29b8032b66814e21c7cf04400567930a7c8f34/dist/aurelia-dependency-injection.d.ts#L8) and the lines below throw TS Error when building:

```
error TS1005: ';' expected.
```

This behavior is since yesteday, so presumably [this commit](https://github.com/aurelia/dependency-injection/commit/fd29b8032b66814e21c7cf04400567930a7c8f34) has introduced the problem.

* **Library Version:**
In fact, this problem showed up when using typing from aurelia-dialog 1.0.0

**Please tell us about your environment:**
* **Node Version:**
8.9.1

* **NPM Version:**
5.10.0

* **JSPM OR Webpack AND Version**
JSPM 0.16.53

* **Language:**
TypeScript 2.7.2

**Comment by DrSammyD** [comment]
This issue seems like a bug on the aurelia-dialog not versioning its typings.

This issue comes from the infer keyword not being part of typescript 2.7. It was added in [typescript 2.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html). If you're able to update to typescript 2.8, that would mitigate the issue, but otherwise this should probably go to the other repo.
