### ISSUE TITLE
Cointainer get new instance

### ISSUE THREAD

**Issue by djindjic** [aurelia/dependency-injection#5]
I have realized that Container.get method returns same instance whenever it's called. I have tried to put this test case and it fails:

``` js
    class Logger {}

    class App {
      static inject() { return [Logger]; };
      constructor(logger) {
        this.logger = logger;
      }
    }

    var container = new Container();
    var firstApp = container.get(App);
    var secondApp = container.get(App);

    expect(firstApp).not.toBe(secondApp);
```

Do I need to create new container instance every time when I want new instance of `App` class?

**Comment by rborosak** [comment]
I need multiple instances of the same viewModel class to be active at the same time (I have a tree view on the left side of the screen and as I click the node in the treeview the right side is populated with data. Every node has it's own instance of viewModel)
I copied routerView element and changed process method to read the viewModel from cache (based on the route fragment). This works but it feels like it's the wrong place to do it because aurelia creates the viewModel somewhere before the process method and then if I have a viewModel in the cache I discard the created view model. (This works because I have registered my view models as transient). 
I would like to read my cache (based on the route fragment) before Aurelia creates the view model and if the view model exists in the cache pass that down the pipeline. 
Is that even possible? Were is the best place to do it?
