### ISSUE TITLE
autoinject not working

### ISSUE THREAD

**Issue by unional** [aurelia/dependency-injection#67]
This test fail with `Expected Logger({  }) to be undefined.`

https://github.com/unional/dependency-injection/blob/master/test/injection.spec.js

I was trying to use it in my TypeScript file with the same result.

Tried `@autoinject()` too.

**Comment by unional** [comment]
The typescript files are transpiled at runtime through `systemjs`/`jspm`.

**Comment by EisenbergEffect** [comment]
You can't inject logger. It's constructor cannot be called. You must use the `getLogger` function instead.

**Comment by unional** [comment]
The `Logger` is an empty class, not the actual `Logger`, it can be just `ClassA`. It can be injected through `inject(Logger)(App1)` or `@inject`, but not `@autoinject`.

**Comment by EisenbergEffect** [comment]
You probably don't have your TypeScript build setup correctly then. You should have something like this:

```
{
	"compilerOptions":{
		"target": "ES5",
		"module": "system",
		"emitDecoratorMetadata": true,
    "experimentalDecorators": true
	}
}
```

**Comment by unional** [comment]
Ar, yes! That's what it is. :) Thanks!

Is there a way to do the same on babel? Would like to contribute a PR and add that test in.

**Comment by EisenbergEffect** [comment]
There's no way to use `autoinject` with Babel because it doesn't have the notion of type metadata. However, there is a community member that wrote a babel plugin that would generate the type metadata so that you didn't need to use inject or autoinject at all, but could just put the types in the constructor. I'm not sure how solid that is though...but it's something that can be done as a Babel plugin.

**Comment by unional** [comment]
I see. Might take a look at it.
I know there is a typescript preprocessor for karma, but I couldn't get it to work in the past.
