### ISSUE TITLE
Typescript: injecting Element class though constructor does not work

### ISSUE THREAD

**Issue by ppn2** [aurelia/dependency-injection#77]
Inject Element class though constructor.
```
import {BindingEngine, customElement} from 'aurelia-framework';
@customElement("some-class")
export class SomeClass {
   constructor(element: Element, bindingEngine: BindingEngine) {
     //does not work. element is an empty object.
     //however injecting any other object works. i.e. bindingEngine is fine.
   }
}
```
Inject Element class though inject attribute
```
import {inject, customElement} from 'aurelia-framework';
@customElement("some-class")
@inject(Element, BindingEngine)
export class SomeClass {
   constructor(private element: Element, private bindingEngine: BindingEngine) {
     //this works
   }
}
```

**Comment by PascalPrecht** [comment]
@ppn2 the problem here is probably that TS doesn't know that is has to emit metadata. It only does that when there's at least one decorator on that class, which is the case when using `@inject()`

I think you'd need to use `@autoinject()` here.

**Comment by EisenbergEffect** [comment]
Yes, that is correct. You have to at least have one decorator on the class for TS to emit the metadata. We created the `autoinject` decorator so that you have a decorator to add even if you don't need one for any other purpose. Ultimately, it would be nice if TS could just be configured to emit type metadata for all constructors automatically. In that case, autoinject wouldn't be needed at all.

That's the first bit. However, I am intrigued that you say injecting the binding engine works somehow automatically. I can't see how that would be the case without some decorator. Can you confirm?

**Comment by ppn2** [comment]
Sorry didn't see the subsequent conversation on this. @PascalPrecht, @EisenbergEffect  What you describe is true. However in my example above I kept it simple for discussion sake. In my code other decorators are present and typescript is generating the __decorate bits. Right now I am using aurelia-framework version 1.0.0-beta.1.2.2 and I can still reproduce above behavior. I am modifying the example above for better clarity.

**Comment by EisenbergEffect** [comment]
Looking into TypeScript, it seems that the problem is that `Element` is an interface in TypeScript even though it's actually a base class in JavaScript. Because it is defined as an interface, it doesn't get written into the metadata by TypeScript and thus can't be auto-injected.

**Comment by JayByfordRewAtTorFx** [comment]
This example from the Hub shows the same issue, 'style' is not a property !

import {autoinject} from 'aurelia-framework';

@autoinject
export class RedSquareCustomAttribute {
  constructor(private element: Element){
      this.element.style.width = this.element.style.height = '100px';
      this.element.style.backgroundColor = 'red';
  }
}

**Comment by RomkeVdMeulen** [comment]
I'm running into this, but only during in-browser transpilation by SystemJS during my Karma run. With off-line transpilation, the Element type is properly emitted as metadata. I can't figure it out.

Off-line transpilation:
```js
MyComponent = MyComponent_1 = tslib_1.__decorate([
        aurelia_property_injection_1.autoinject,
        aurelia_framework_1.processContent(false),
        tslib_1.__metadata("design:paramtypes", [Element])
    ], MyComponent);
```

In-browser transpilation:
```js
MyComponent = tslib_1.__decorate([
                aurelia_property_injection_1.autoinject,
                aurelia_framework_1.processContent(false),
                tslib_1.__metadata("design:paramtypes", [Object])
            ], MyComponent);
```

**Comment by RomkeVdMeulen** [comment]
Microsoft/TypeScript#8355 may be related to this.

**Comment by RomkeVdMeulen** [comment]
So from what I understand: when doing in-browser transpilation TypeScript always uses the `isolatedModules` option, meaning that while transpiling a source file the transpiler only looks at that file and its imports, rather than the whole project. I'm guessing there's a real `Element` type somewhere in my project, so that during off-line transpilation its not seen as an interface and gets added to the metadata. Not so with `isolatedModules`: the only `Element` it sees is the interface in the TypeScript DOM library, so it's serialized to metadata as `Object`.

It seems [there's been some discussion](https://github.com/Microsoft/TypeScript/issues/3148) about emitting interfaces in metadata, but for now it doesn't look like it's coming anytime soon.

Two possible workarounds I can think of: use `@inject` or `static inject` rather than `@autoinject`, or for every interface you want to `@autoinject` add something like this to the file:

```ts
declare class Element {};
```
